# LLM
model_name: gpt-4
simple_model_name: gpt-3.5-turbo-16k 

api_key: "add your apikey"

# Local models
local_model:
  categorize_battery_paper: path for Fine-tuned llm models
  paragraph_classification: path for Fine-tuned llm models

# Fine-tuned llm models (optional)
fine_tuning_models:
  ft_paper_categorize: add Fine-tuned llm models
  ft_text_property_type: add Fine-tuned llm models
  ft_text_property_extract: add Fine-tuned llm models

  
# Use local models flag
use_local_models: false

# LLM Options
temperature: 0.0
verbose: False

# config - agent
reconstruct: True   # Merge paragraph for reducing tokens
input_max_tokens_property: 3500        # max tokens for property
